apiVersion: apps/v1
kind: Deployment
metadata:
  app: bgd
  name: bgd
spec:
  selector:
    matchLabels:
      app: bgd
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
        - name: bgd
          image: quay.io/redhatworkshops/bgd:latest
          env:
          - name: COLOR
            value: "blue"
            resources: {}
          
