apiVersion: apps/v1
kind: Deployment
metadata:
  app: bgd
  name: bgd
spec:
  selector:
    matchLabels:
      app: bgd
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
        - name: bgd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          