kind: Route
apiVersion: route.openshift.io/v1
metadata:
  creationTimestamp: null
  namespace: eportal-staging
  name: bgd
  labels: 
    app: bgd
  
spec:
  host: "bgd.apps.go.ocp.redhatworkshops.io"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bgd
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
