kind: Service
apiVersion: v1
metadata:
  annotations:
    idling.alpha.openshift.io/idled-at: '2023-08-30T19:00:32Z'
    idling.alpha.openshift.io/unidle-targets: >-
      [{"kind":"Deployment","name":"eportal-liferays-prod","group":"apps","replicas":1}]
    kubectl.kubernetes.io/last-applied-configuration: >
       {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":"2023-08-29T06:21:42Z","labels":{"app":"liferaytest","app.kubernetes.io/component":"liferaytest","app.kubernetes.io/instance":"liferaytest","app.kubernetes.io/name":"liferaytest","app.kubernetes.io/part-of":"liferay-test"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:openshift.io/generated-by":{}},"f:labels":{".":{},"f:app":{},"f:app.kubernetes.io/component":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/part-of":{}}},"f:spec":{"f:clusterIP":{},"f:clusterIPs":{},"f:internalTrafficPolicy":{},"f:ipFamilies":{},"f:ipFamilyPolicy":{},"f:ports":{".":{},"k:{\"port\":11311,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":8000,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":8009,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":8080,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":8081,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}},"manager":"argocd-controller","operation":"Update","time":"2023-08-29T06:21:42Z"}],"name":"liferaytest","namespace":"eportal-staging","resourceVersion":"6888276318","uid":"dab494ff-ba74-4db6-9d9e-536f65bb9ce5"},"spec":{"clusterIP":"10.125.161.28","clusterIPs":["10.125.161.28"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"11311-tcp","port":11311,"protocol":"TCP","targetPort":11311},{"name":"8000-tcp","port":8000,"protocol":"TCP","targetPort":8000},{"name":"8009-tcp","port":8009,"protocol":"TCP","targetPort":8009},{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080},{"name":"8081-tcp","port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"liferaytest","deployment":"liferaytest"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    openshift.io/generated-by: OpenShiftWebConsole 
  creationTimestamp: '2023-08-29T06:21:42Z'
  name: eportal-liferays-prod   
  namespace: eportal-staging
spec:
  clusterIP: 
  clusterIPs:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 11311-tcp
      protocol: TCP
      port: 11311
      targetPort: 11311
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: 8009-tcp
      protocol: TCP
      port: 8009
      targetPort: 8009
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
