kind: Service
apiVersion: v1
metadata:
  name: eportal-liferays
  namespace: eportal-staging
  creationTimestamp: '2023-07-18T08:55:41Z'
  labels:
    app: eportal-liferays
    app.kubernetes.io/component: eportal-liferays
    app.kubernetes.io/instance: eportal-liferays
    app.kubernetes.io/name: eportal-liferays
    app.kubernetes.io/part-of: eportal-liferays-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: Mozilla
      operation: Update
      time: '2023-07-18T08:55:41Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubectl.kubernetes.io/last-applied-configuration': {}	
      manager: argocd-controller	
      operation: Update	
      time: '2023-09-04T09:08:00Z'
spec:
  clusterIP: 
  ipFamilies:
    - IPv4
  ports:
    - name: 11311-tcp
      protocol: TCP
      port: 11311
      targetPort: 11311
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: 8009-tcp
      protocol: TCP
      port: 8009
      targetPort: 8009
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  clusterIPs:
   
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: eportal-liferays
    deployment: eportal-liferays
status:
  loadBalancer: {}
